Gotensfer/Taller-VI

Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
FMod/TallerVI_Banks_FMod/Metadata/Asset/{fc6584ef-0a67-4da6-9a73-f0d35d9dd0d0}.xml
FMod/TallerVI_Banks_FMod/Metadata/Bank/{2958e332-066a-434a-8711-c82fc6d738b5}.xml
FMod/TallerVI_Banks_FMod/Metadata/BankFolder/{f913c9d2-d237-4a9a-be62-600d5e80706f}.xml
FMod/TallerVI_Banks_FMod/Metadata/EffectPresetFolder/{7617a003-2cce-4ee0-a60a-97a5fbb76f43}.xml
FMod/TallerVI_Banks_FMod/Metadata/EncodingSetting/{1a02028c-e8e6-4206-9035-b9f5890fbf78}.xml
FMod/TallerVI_Banks_FMod/Metadata/EventFolder/{2651a9c5-8335-40c1-9b67-27766f813af2}.xml
FMod/TallerVI_Banks_FMod/Metadata/Master.xml
FMod/TallerVI_Banks_FMod/Metadata/Mixer.xml
FMod/TallerVI_Banks_FMod/Metadata/ParameterPresetFolder/{2962a977-f972-4bd1-a150-c55665b96891}.xml
FMod/TallerVI_Banks_FMod/Metadata/Platform/{6dceaa0a-a240-46a9-9643-68a0b14a4695}.xml
FMod/TallerVI_Banks_FMod/Metadata/ProfilerFolder/{d12eddef-cbbb-4401-a61a-79d74a583d8e}.xml
FMod/TallerVI_Banks_FMod/Metadata/Return/{6df5a893-18f5-4bf8-9654-c74250229fdd}.xml
FMod/TallerVI_Banks_FMod/Metadata/SandboxFolder/{cfbe4fa5-aba2-4074-9f6f-a40631b90819}.xml
FMod/TallerVI_Banks_FMod/Metadata/SnapshotGroup/{c711ef45-95e2-44b2-a178-a57955739a57}.xml
FMod/TallerVI_Banks_FMod/Metadata/Tags.xml
FMod/TallerVI_Banks_FMod/Metadata/Workspace.xml
FMod/TallerVI_Banks_FMod/TallerVI_Banks_FMod.fspro
ProjectSettings/AudioManager.asset

FMod configuración

---

.idea/.idea.Taller-VI/.idea/projectSettingsUpdater.xml
.idea/.idea.Taller-VI/.idea/workspace.xml
Assets/Scenes/Pre Alpha/0.1.unity
Assets/Scenes/Pre Alpha/Aim_Module.unity
Assets/Scenes/Pre Alpha/Aim_Module.unity.meta
Assets/Scripts/UIInterface.cs
Assets/Scripts/UIInterface.cs.meta

Se cambia el reset del jugador al UI_Manager por medio del script "UIInterface"
Copié el pedacito de código de SceneManager que tenía el jugador y lo puse en el scrip anteriormente descrito.

Reset -> UI Manager

---

Assets/2D Sprites/Testing/Test_PowerUpBasic.png
Assets/2D Sprites/Testing/Test_PowerUpBasic.png.meta
Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
Assets/Scenes/Pre Alpha/PowerUp_Basic.unity
Assets/Scenes/Pre Alpha/PowerUp_Basic.unity.meta
Assets/Scripts test/PowerUp_Basic.cs
Assets/Scripts test/PowerUp_Basic.cs.meta

Se implemento un power-up MUY rudimentario (Tan rudimentario que se encuentra en la parte de - Scripts Test - ) que impulsa al jugador en diagonal hasta 3 veces.
Tanto la dirección como la fuerza de este impulso se encuentra serializado, por lo que se puede acomodar rápidamente para futuras pruebas (La dirección se normaliza de forma automática sin importar el vector que se meta para evitar resultados extraños)

Power up basic 

---

TallerVI Unity/Assets/Prefabs.meta
TallerVI Unity/Assets/Prefabs/PowerUp Pidgeon.prefab
TallerVI Unity/Assets/Prefabs/PowerUp Pidgeon.prefab.meta
TallerVI Unity/Assets/Scenes/Pre Alpha/0.3 Pidgeon.unity
TallerVI Unity/Assets/Scenes/Pre Alpha/0.3 Pidgeon.unity.meta
TallerVI Unity/Assets/Scripts test/PidgeonPickUp.cs
TallerVI Unity/Assets/Scripts test/PidgeonPickUp.cs.meta
TallerVI Unity/Assets/Scripts test/PowerUp_PidgeonTest.cs
TallerVI Unity/Assets/Scripts test/PowerUp_PidgeonTest.cs.meta

Se implemento usando la clase `PowerUp_PidgeonTest` y `PidgeonPickUp`
La clase `PowerUp_PidgeonTest` representa la funcionalidad del powerup y en esta se encuentra todo su funcionamiento.
La clase `PidgeonPickUp` representa el Picku up del power up como tal, lo cual permite que el jugador al colisionar con esta active la funcionalidad **Agregando como componente** la clase `PowerUp_PidgeonTest` al **GameObject** del jugador. 
Para editar los valores del power up, se modifica el prefab de _**PowerUp Pidgeon**_ encontrado en la nueva carpeta "prefabs".
**Power Up Time** es el tiempo que dura el power up.
**Speed** es la magnitud de la velocidad con la que se mueve el jugador al usar el power up.
**Sensibility** es la sensibilidad al "touch swipe" para mover hacia arriba/abajo al jugador …

Pidgeon power up

---

TallerVI Unity/Assets/2D Animations/Cacaleta/Cacaleta_Animations.controller
TallerVI Unity/Assets/Scenes/Pre Alpha/0.5 Animations.unity

Se actualiza el animator controller

Update pr previo

---

TallerVI Unity/Assets/Scenes/Pre Alpha/0.6 PowerUpsFix.unity
TallerVI Unity/Assets/Scenes/Pre Alpha/0.6 PowerUpsFix.unity.meta
TallerVI Unity/Assets/Scripts/LaunchModule.cs
TallerVI Unity/Assets/Scripts/PowerUp_Base.cs
TallerVI Unity/Assets/Scripts/Spawner_Module.cs

Mejoras a pooling e implementacion recogible

Ajustes a generacion e implementacion nuevo recogible

---

TallerVI Unity/Assets/Scenes/Pre Alpha/0.6 EcoSys - Earn coins.unity
TallerVI Unity/Assets/Scenes/Pre Alpha/0.6 EcoSys - Earn coins.unity.meta
TallerVI Unity/Assets/Scriptable objects/Foods/Desserts/Bocadillo.asset
TallerVI Unity/Assets/Scriptable objects/Foods/Desserts/Flan.asset
TallerVI Unity/Assets/Scriptable objects/Foods/Drinks/Beer.asset
TallerVI Unity/Assets/Scriptable objects/Foods/Drinks/Guaro.asset
TallerVI Unity/Assets/Scriptable objects/Foods/Drinks/Soda.asset
TallerVI Unity/Assets/Scriptable objects/Foods/Main dishes/Ajiaco.asset
TallerVI Unity/Assets/Scriptable objects/Foods/Main dishes/Bandeja paisa.asset
TallerVI Unity/Assets/Scriptable objects/Foods/Main dishes/Bocachico.asset
TallerVI Unity/Assets/Scriptable objects/Game data.meta
TallerVI Unity/Assets/Scriptable objects/Game data/CoinPerDistance Config.asset
TallerVI Unity/Assets/Scriptable objects/Game data/CoinPerDistance Config.asset.meta
TallerVI Unity/Assets/Scripts/CoinPerDistanceData.cs
TallerVI Unity/Assets/Scripts/CoinPerDistanceData.cs.meta
TallerVI Unity/Assets/Scripts/CoinsPerDistanceTracker_Module.cs
TallerVI Unity/Assets/Scripts/CoinsPerDistanceTracker_Module.cs.meta
TallerVI Unity/Assets/Scripts/EcoLoader.cs
TallerVI Unity/Assets/Scripts/EcoLoader.cs.meta
TallerVI Unity/Assets/Scripts/EconomyData.cs
TallerVI Unity/Assets/Scripts/EconomyData.cs.meta
TallerVI Unity/Assets/Scripts/Food.cs
TallerVI Unity/Assets/Scripts/PlayerStop_Module.cs

Se implemento el sistema de economia usando playerprefs
Se agregaro las clase `EconomyData` que es una clase estática para mantener registro de los datos de la economía y a su vez servir como intermediario para realizar operaciones economicas como ganar, gastar, resetear, setear, cargar.
Para la ganancia de monedas se creo un scriptable object para llevar la configuración de ganancia y otra clase que se encarga de calcular el dinero ganado con base en la configuración en StatTracker
Queda implementar con UI en Develop

Sistema de economía

---

TallerVI Unity/Assets/Scripts/FPSDebug.cs
TallerVI Unity/Assets/Scripts/FPSDebug.cs.meta
TallerVI Unity/Assets/Scripts/GameLoad_DataInitializer.cs

Se añadio un script para mostrar los FPS

FPS Debug y cambios en orden para DataInitializer

---

TallerVI Unity/Assets/2D Animations/Cacaleta/Cacaleta_Animations Fix.controller
TallerVI Unity/Assets/2D Animations/Cacaleta/Cacaleta_Animations Fix.controller.meta
TallerVI Unity/Assets/Scenes/Alpha/1.1 AnimationsFix.unity
TallerVI Unity/Assets/Scenes/Alpha/1.1 AnimationsFix.unity.meta
TallerVI Unity/Assets/Scripts/AnimatorControl_Module.cs

Se solucionan las animaciones.
Se han implementado los nuevos eventos.
Además de que se les quita el "has exit time" para hacer una transición precisa apenas reciba el evento.

Animations Fixed

---

TallerVI Unity/Assets/Scripts/Spawner_Module.cs

Parametrización e implementación niveles de los power ups

Spawner Update

---

TallerVI Unity/Assets/Scenes/Alpha/1.1 Main menu.unity
TallerVI Unity/Assets/Scenes/Alpha/1.1 UI Inprovements.unity
TallerVI Unity/Assets/Scriptable objects/Skins/Cacalien.asset
TallerVI Unity/Assets/Scriptable objects/Skins/Cacalien.asset.meta
TallerVI Unity/Assets/Scriptable objects/Skins/Cacanaut.asset
TallerVI Unity/Assets/Scriptable objects/Skins/Cacanaut.asset.meta
TallerVI Unity/Assets/Scriptable objects/Skins/Cacowboy.asset
TallerVI Unity/Assets/Scriptable objects/Skins/Cacowboy.asset.meta
TallerVI Unity/Assets/Scriptable objects/Skins/Cacsycal.asset
TallerVI Unity/Assets/Scriptable objects/Skins/Cacsycal.asset.meta
TallerVI Unity/Assets/Scripts/DeveloperCheats.cs
TallerVI Unity/Assets/Scripts/SkinData.cs
TallerVI Unity/Assets/Scripts/SkinLoad_Module.cs

Se implementaron las 4 nuevas skins del juego.
Se actualizo el enumerator de `SkinID` para integraciones con otros sistemas.
Se actualizaron los cheats para que ahora cada vez que se presione Q se gane 500 y no 50.

Se implementaron todas las nuevas skins

---

TallerVI Unity/Assets/Scenes/Alpha/1.1 Main menu.unity
TallerVI Unity/Assets/Scripts/DisplayRecordText.cs

Se corrigio el error descrito en la tarea # 223 del HacknPlan.

Bugfixing texto de record

---

TallerVI Unity/Assets/Scenes/Alpha/1.1 Coin tutorial.unity
TallerVI Unity/Assets/Scenes/Alpha/1.1 Coin tutorial.unity.meta
TallerVI Unity/Assets/Scripts/Tutorial_CheckCoins.cs
TallerVI Unity/Assets/Scripts/Tutorial_CheckCoins.cs.meta

Se agregó el check de monedas (Parametrizado) para activar la funcionalidad del tutorial de las mejoras siempre y cuando el jugador: Tenga suficientes monedas, y, No haya hecho aún el tutorial de mejoras "firstTimeUpgrades".
Para implementar:
1) Agregar un nuevo objeto vacío llamado `Tutorial check` en `--- Game Systems ---`.
2) A este objeto `Tutorial check` agregarle la clase `Tutorial_CheckCoins`.
3) Ajustar el campo de `Coins Needed For Tutorial` al valor deseado (Idealmente 300 ya que con ese valor se puede comprar la primera mejora del cohete, NOTA: Sujeto a GD)
4) Subscribir el método `CheckCoins()` que le pertenece a esta clase, al evento de `CrashEvent` del sistema de eventos.
Modifica el código de `Tutorial_CheckCoins`
```CS
public class Tutorial_CheckCoins : MonoBehaviour
{ …
```

Se agrego el check de monedas

---

TallerVI Unity/Assets/Scripts test/Sfx/FmodEventManager.cs

Se añadieron las dos a su respectiva ID y ruta

Implementados cacaruto y golden

---

TallerVI Unity/Assets/2D Sprites/Powerups_VFX/Prefabs/Skins_Mitosis_Legs/Cacaruto_Mitosis_Legs 2.prefab

Golden poop

---

Fmod/DivingPoop/.unsaved/.user/Metadata/Asset/{5e16193e-f6c0-49a8-be24-3be3c4e11116}.user.xml
Fmod/DivingPoop/.unsaved/.user/Metadata/Mixer.user.xml
Fmod/DivingPoop/.unsaved/.user/Metadata/Workspace.user.xml
TallerVI Unity/Assets/Scenes/Alpha/1.2 Main menu.unity

se le pone FmodUi Emitter a todos los botones de las skins que no son el lock

Sonido a los botones de las skins

---

TallerVI Unity/Assets/Scenes/Alpha/1.2 FecalitoFix.unity
TallerVI Unity/Assets/Scenes/Alpha/1.2 FecalitoFix.unity.meta
TallerVI Unity/Assets/Scripts/Fecalito.cs

Los valores de CD por nivel se pueden cambiar aqui:
Respectivamente se asigna el valor de CD para cada nivel, en caso de ser nivel 0 el boton simplemente no estara activo.

FeaclitoFix

---

TallerVI Unity/Assets/PostProcessing.meta
TallerVI Unity/Assets/Scenes/Alpha/Post Processing.meta
TallerVI Unity/Assets/Scenes/Alpha/Post Processing.unity
TallerVI Unity/Assets/Scenes/Alpha/Post Processing.unity.meta
TallerVI Unity/Assets/Scenes/Alpha/Post Processing/20s Profile.asset
TallerVI Unity/Assets/Scenes/Alpha/Post Processing/20s Profile.asset.meta
TallerVI Unity/Assets/Scenes/Alpha/Post Processing/20sVolume.prefab
TallerVI Unity/Assets/Scenes/Alpha/Post Processing/20sVolume.prefab.meta

Se crea un volumen global para pasar todo a escala de grises en la skin de los años 20.
El como se implemente se sale de mi control. Pienso que debería activarse y desactivarse el volumen cuando se lance la skin(?

Post Processing para la skin de los 20s

---

TallerVI Unity/Assets/Scenes/Alpha/Animación final.unity
TallerVI Unity/Assets/Scenes/Alpha/Escena de felicitaciones.unity
TallerVI Unity/Assets/Scenes/Alpha/Escena de felicitaciones.unity.meta
TallerVI Unity/Assets/Scripts/CongratulateScreen.cs
TallerVI Unity/Assets/Scripts/CongratulateScreen.cs.meta
TallerVI Unity/Assets/Scripts/EndGameCinematic.cs
TallerVI Unity/Assets/Scripts/EndGameCinematic.cs.meta
TallerVI Unity/Assets/Scripts/EndGame_Module.cs
TallerVI Unity/Assets/Scripts/PlayerStop_Module.cs

Sistema completo de término de partida

End game cinematic

---

TallerVI Unity/Assets/Samples/In App Purchasing.meta
TallerVI Unity/Assets/Samples/In App Purchasing/4.4.1.meta
TallerVI Unity/Assets/Samples/In App Purchasing/4.4.1/Google Play Store - 02 Restoring Transactions.meta
TallerVI Unity/Assets/Samples/In App Purchasing/4.4.1/Google Play Store - 02 Restoring Transactions/.sample.json
TallerVI Unity/Assets/Samples/In App Purchasing/4.4.1/Google Play Store - 02 Restoring Transactions/README.md
TallerVI Unity/Assets/Samples/In App Purchasing/4.4.1/Google Play Store - 02 Restoring Transactions/README.md.meta
TallerVI Unity/Assets/Samples/In App Purchasing/4.4.1/Google Play Store - 02 Restoring Transactions/RestoringTransactions.cs
TallerVI Unity/Assets/Samples/In App Purchasing/4.4.1/Google Play Store - 02 Restoring Transactions/RestoringTransactions.cs.meta
TallerVI Unity/Assets/Samples/In App Purchasing/4.4.1/Google Play Store - 02 Restoring Transactions/RestoringTransactions.unity
TallerVI Unity/Assets/Samples/In App Purchasing/4.4.1/Google Play Store - 02 Restoring Transactions/RestoringTransactions.unity.meta
TallerVI Unity/Assets/Samples/In App Purchasing/4.4.1/Google Play Store - 02 Restoring Transactions/UserWarningGooglePlayStore.cs
TallerVI Unity/Assets/Samples/In App Purchasing/4.4.1/Google Play Store - 02 Restoring Transactions/UserWarningGooglePlayStore.cs.meta
TallerVI Unity/Assets/Scenes/Release/1.0.1 Game.unity
TallerVI Unity/Assets/Scenes/Release/1.0.1 Main menu.unity
TallerVI Unity/Assets/Scripts/SkinStoreElement.cs
TallerVI Unity/Assets/Scripts/Summary.cs
TallerVI Unity/ProjectSettings/ProjectSettings.asset

7h
7h
7 putas horas cuadrando la restauración de las compras

Unity iaps

---

TallerVI Unity/Assets/Scenes/Release/1.0.1 Game.unity
TallerVI Unity/Assets/Scripts/ResetAllData.cs
TallerVI Unity/ProjectSettings/ProjectSettings.asset

Versión final de proyecto a la version 1.0.1 Release (K)

Ajustes finales para 1.0.1
